Feature 12th
lifetimenq/react-redux pull request #2
Opened 2021-01-15 15:08 UTC by lifetimenq

2021-01-16 12:47 UTC, index01d requested changes

2021-01-16 12:47 UTC, index01d commented on src/Components/ChapterList/ChapterList.js
> +      content.present.entries.chapters.map(
лучше передавать в презентационный компонент готовый список глав, извлекать его из ключей present.entries нужно в контейнерной части (mapStateToProps)

2021-01-16 12:47 UTC, index01d commented on src/Components/ChapterList/index.js
>      ...state,
точно ли компоненту требуется весь state?

2021-01-16 12:47 UTC, index01d commented on src/Components/SubChapterList/index.js
>      ...state,
точно ли компоненту нужен весь state?

2021-01-16 12:47 UTC, index01d commented on src/Components/SubChapterList/index.js
> +      chapters: state.content.present.entries.chapters.filter(filters[state.filters]),
стоило бы определить переменную chapters, чтобы избежать дублирования длинной небезопасной навигации по state

2021-01-17 19:33 UTC, lifetimenq commented on src/Components/ChapterList/ChapterList.js
> +      content.present.entries.chapters.map(
https://github.com/lifetimenq/react-redux/commit/5b04c8414ebd0d17a2e5af76f9c92d01db58214e
исправил

2021-01-17 19:33 UTC, lifetimenq commented on src/Components/ChapterList/index.js
>      ...state,
https://github.com/lifetimenq/react-redux/commit/5b04c8414ebd0d17a2e5af76f9c92d01db58214e
достаточно isLoading и chapters

2021-01-17 19:39 UTC, lifetimenq commented on src/Components/SubChapterList/index.js
>      ...state,
https://github.com/lifetimenq/react-redux/commit/6d34abf1766c7841f2b25efc369ed3bea3f88294
тут достаточно только subChapters

2021-01-17 19:40 UTC, lifetimenq commented on src/Components/SubChapterList/index.js
> +      chapters: state.content.present.entries.chapters.filter(filters[state.filters]),
https://github.com/lifetimenq/react-redux/commit/6d34abf1766c7841f2b25efc369ed3bea3f88294
там достаточно только subChapters, для 1-го вызова можно не объявлять переменную, учту на будущее если похожая ситуация возникнет

2021-01-18 12:25 UTC, index01d approved these changes

2021-01-18 16:25 UTC, merged